'use client';

import { SparklesIcon } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { BestSellingProductsView } from './best-selling-products-view';
import { DemandForecastView } from './demand-forecast-view';
import { ImportRecommendationView } from './import-recommendation-view';
import { PredictiveChartsView } from './predictive-charts-view';
import { SeasonalAnalysisView } from './seasonal-analysis-view';
import { SlowMovingInventoryView } from './slow-moving-inventory-view';

/**
 * AI Dashboard (Phase 8.13) — explicitly a demo-only placeholder module per
 * `project_description.txt` (Module 13): "do NOT integrate any real AI." Two sections
 * (Best Selling Products, Slow Moving Inventory) are real aggregations over sales/inventory
 * data; the other four (Demand Forecast, Seasonal Analysis, Import Recommendation, Predictive
 * Charts) are randomly generated by `apps/api/src/shared/integrations/aiForecasting.service.ts`
 * purely to populate demo charts. The banner below plus each demo section's `<DemoDataBadge />`
 * keep that distinction visible to anyone viewing the demo, matching the tone of the Tax module's
 * "not integrated" e-invoice screen (`src/features/tax/e-invoice-view.tsx`).
 */
export function AiDashboardView() {
  return (
    <div className="flex flex-col gap-6">
      <Alert>
        <SparklesIcon />
        <AlertTitle>Demo-only forecasting</AlertTitle>
        <AlertDescription>
          This dashboard does not integrate any real AI or machine learning service. Best Selling
          Products and Slow Moving Inventory below are computed from real sales and inventory
          records; Demand Forecast, Seasonal Analysis, Import Recommendation, and Predictive
          Charts (each marked &ldquo;Demo data&rdquo;) show randomly generated placeholder numbers
          for demonstration purposes only.
        </AlertDescription>
      </Alert>

      <section className="flex flex-col gap-4">
        <h2 className="text-lg font-semibold tracking-tight">Sales &amp; Inventory Insights</h2>
        <div className="grid gap-4 xl:grid-cols-2">
          <BestSellingProductsView />
          <SlowMovingInventoryView />
        </div>
      </section>

      <section className="flex flex-col gap-4">
        <h2 className="text-lg font-semibold tracking-tight">Demo-Generated Forecasts</h2>
        <DemandForecastView />
        <div className="grid gap-4 xl:grid-cols-2">
          <SeasonalAnalysisView />
          <ImportRecommendationView />
        </div>
        <PredictiveChartsView />
      </section>
    </div>
  );
}
